### PR TITLE
getSelection documentation added

### PR DESCRIPTION
**Pull request by DimaUndSo**
getSelection documentation added

### CODE REVIEW

**Comment by sekodev** [comment]
@DimaUndSo do those changes affect TextBox as well? I see you've added a reference for getSelection to TextBox docs but didn't create a page for it.

**Comment by DimaUndSo** [comment]
> @DimaUndSo do those changes affect TextBox as well? I see you've added a reference for getSelection to TextBox docs but didn't create a page for it.

I have added code for textBox, but haven't tested it yet. I only tested textField.
Also I was a little confused why Android does not have a textBox.cpp file at all, since all other platforms have it. (I would expect a file like Rtt_AndroidTextBoxObject.cpp. 
So I can not guarantee that getSelection for textBox is working, but feel free to try it out. If it works well on all platforms we can add the documentation for it too.

**Comment by DimaUndSo** [comment]
> @DimaUndSo do those changes affect TextBox as well? I see you've added a reference for getSelection to TextBox docs but didn't create a page for it.

Ok, I have tested it on all devices and added the documentation for textBox too.

**Comment by sekodev** [comment]
That's amazing! Thank you.

**Pull request merged**
